apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: acme-fitness-ingress
  namespace: workloads
spec:
  virtualhost:
    fqdn: acme-fitness.tap-lab.terasky.demo
    tls:
      passthrough: true
  tcpproxy:
    services:
    - name: acme-fitness-gateway
      port: 443
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-fitness-cert
  namespace: workloads
spec:
  commonName: acme-fitness.tap-lab.terasky.demo
  dnsNames:
  - acme-fitness.tap-lab.terasky.demo
  issuerRef:
    name: tap-ingress-selfsigned
    kind: ClusterIssuer
  secretName: acme-fitness-cert