apiVersion: servicebinding.io/v1beta1
kind: ServiceBinding
metadata:
  name: sso-cert
spec:
  name: sso-cert
  service:
    apiVersion: v1
    kind: Secret
    name: tap-ca-cert
  workload:
    apiVersion: apps/v1
    kind: Deployment
    name: scg-operator