apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-fitness-gateway
  namespace: workloads
  description: ACME Fitness API Gateway
  tags:
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=acme-fitness-gateway'
    'backstage.io/techdocs-ref': dir:../.
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
  dependsOn:
  - component:workloads/acme-shopping