apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: acme-cart-redis
  namespace: workloads
  description: ACME Fitness Store Cart Service Cache
  tags:
    - java
    - spring
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'service=cart-redis'
    'backstage.io/techdocs-ref': dir:../.
spec:
  type: service
  lifecycle: production
  owner: default-team
  system: fitness-store
